In [68]:
%load_ext autoreload
%autoreload 2

from datasets import load_dataset
import pandas as pd
from evaluator import Evaluator

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
splits = load_dataset("ecaplan/splits", "splits")
splits = splits['train']

Generating train split: 176686 examples [01:25, 2055.97 examples/s]

In [ ]:
# convert the dataset to a pandas dataframe
df = pd.DataFrame(splits)

In [77]:
df

,description,sample_A,sample_B,demographic_A,demographic_B,switched,example_posts,category,prediction,correct
0,3D Printing,"[[Doug Dimmadome, owner of the Dimmsdale Dimma...",[**Your submission has been removed for one or...,black,catholic,False,[> He got a 3d printer\n\nDude he got a 250K d...,Technology & Gaming,True,False
1,3D Printing,[[Here](http://theverge.com/2013/5/3/4297612/s...,"[Isn't that game already 3D by design? , So oc...",black,catholic,True,"[Yea, I think that was the movie that killed 3...",Technology & Gaming,True,True
2,3D Printing,[I don't really know. The 3DS players say that...,[It depends what sort of games you're into. Of...,black,catholic,False,[It will be interesting to see that instead of...,Technology & Gaming,False,True
3,3D Printing,[>I cannot find a single showing of Thor that ...,[I would suggest the form 2 series printers. T...,black,catholic,False,[First you bring up the idea of 3D printed gun...,Technology & Gaming,False,True
4,3D Printing,[So apparently the world no longer makes the m...,[This is because the 3DS has fewer pixels to w...,black,catholic,False,[Gha... Just found this list. It's bad. Too ma...,Technology & Gaming,False,True
...,...,...,...,...,...,...,...,...,...,...
176681,Yoga,"[So... yoga pants? , Yoga is fine. It's just e...",[(hugs) I'm sure every single person in that c...,jewish,teacher,False,[There are many things that make people better...,Sports & Fitness,True,False
176682,Yoga,"[> sure, other religious practices can be dang...",[I have one that looks similar...wraps up a yo...,jewish,teacher,False,[I thank god for the current yoga pants thing ...,Sports & Fitness,True,False
176683,Yoga,[When I hit 30lbs I’m going to reward myself w...,[Unfortunately due to allergies this is why I ...,jewish,teacher,False,"[Starting point: I've had several, but I suppo...",Sports & Fitness,False,True
176684,Yoga,"[up there with companion animals, yoga and med...",[Try yoga! I do that when I don't want to go t...,jewish,teacher,False,"[If you want to practice *real* yoga, then no....",Sports & Fitness,True,False
176685,Yoga,[I'm Catholic and there is nothing wrong with ...,[I had 2 hot female teachers who ALWAYS wore y...,jewish,teacher,True,[Add yoga or swimming to your routine to loose...,Sports & Fitness,False,False

In [26]:
small_df = df.sample(1000, random_state=42)

In [ ]:
e = Evaluator(df, test=True)

In [70]:
e.evaluate()

,description,sample_A,sample_B,demographic_A,demographic_B,switched,example_posts,category,prediction,correct
0,3D Printing,"[[Doug Dimmadome, owner of the Dimmsdale Dimma...",[**Your submission has been removed for one or...,black,catholic,False,[> He got a 3d printer\n\nDude he got a 250K d...,Technology & Gaming,False,True
1,3D Printing,[[Here](http://theverge.com/2013/5/3/4297612/s...,"[Isn't that game already 3D by design? , So oc...",black,catholic,True,"[Yea, I think that was the movie that killed 3...",Technology & Gaming,True,True
2,3D Printing,[I don't really know. The 3DS players say that...,[It depends what sort of games you're into. Of...,black,catholic,False,[It will be interesting to see that instead of...,Technology & Gaming,True,False
3,3D Printing,[>I cannot find a single showing of Thor that ...,[I would suggest the form 2 series printers. T...,black,catholic,False,[First you bring up the idea of 3D printed gun...,Technology & Gaming,False,True
4,3D Printing,[So apparently the world no longer makes the m...,[This is because the 3DS has fewer pixels to w...,black,catholic,False,[Gha... Just found this list. It's bad. Too ma...,Technology & Gaming,True,False
...,...,...,...,...,...,...,...,...,...,...
176681,Yoga,"[So... yoga pants? , Yoga is fine. It's just e...",[(hugs) I'm sure every single person in that c...,jewish,teacher,False,[There are many things that make people better...,Sports & Fitness,False,True
176682,Yoga,"[> sure, other religious practices can be dang...",[I have one that looks similar...wraps up a yo...,jewish,teacher,False,[I thank god for the current yoga pants thing ...,Sports & Fitness,True,False
176683,Yoga,[When I hit 30lbs I’m going to reward myself w...,[Unfortunately due to allergies this is why I ...,jewish,teacher,False,"[Starting point: I've had several, but I suppo...",Sports & Fitness,False,True
176684,Yoga,"[up there with companion animals, yoga and med...",[Try yoga! I do that when I don't want to go t...,jewish,teacher,False,"[If you want to practice *real* yoga, then no....",Sports & Fitness,True,False
176685,Yoga,[I'm Catholic and there is nothing wrong with ...,[I had 2 hot female teachers who ALWAYS wore y...,jewish,teacher,True,[Add yoga or swimming to your routine to loose...,Sports & Fitness,True,True

In [74]:
split_reports = e.get_all_split_reports()

In [76]:
for split_type, report in split_reports.items():
    print(f"Split: {split_type}")
    display(report)

Split: Split by (demographic_A, demographic_B)

      demographic_A    demographic_B  count  accuracy
0             black         catholic  17644  0.501417
1             black     construction  11261  0.502531
2             black  hindu_jain_sikh   4699  0.496063
3             black           jewish  16231  0.500647
4             black          teacher  17647  0.497025
5          catholic     construction  11830  0.497718
6          catholic  hindu_jain_sikh   4710  0.489809
7          catholic           jewish  17772  0.499212
8          catholic          teacher  20353  0.504594
9      construction  hindu_jain_sikh   4631  0.495357
10     construction           jewish  11179  0.483406
11     construction          teacher  11749  0.495702
12  hindu_jain_sikh           jewish   4710  0.491720
13  hindu_jain_sikh          teacher   4689  0.505012
14           jewish          teacher  17581  0.502247

Split: Split by (unique demographic)

  unique_demographic  count  accuracy
0       construction  50650  0.494946
1           catholic  72309  0.500408
2    hindu_jain_sikh  23439  0.495584
3            teacher  72019  0.500743
4              black  67482  0.499896
5             jewish  67473  0.497206

Split: Split by (category)

                                category  count  accuracy
0                   Education & Academia  17469  0.497281
1                  Entertainment & Media  17650  0.501303
2                    Finance & Investing  17800  0.495393
3            Hobbies & Special Interests  17590  0.508186
4                          Humor & Memes  17718  0.502314
5                  News & Current Events  17572  0.494935
6  Professional & Career-oriented Spaces  17711  0.492011
7                       Sports & Fitness  17685  0.499632
8                    Technology & Gaming  17828  0.496803
9                     Travel & Geography  17663  0.498839

Split: Split by (category, demographic_A, demographic_B)

                 category    demographic_A    demographic_B  count  accuracy
0    Education & Academia            black         catholic   1851  0.501351
1    Education & Academia            black     construction   1032  0.505814
2    Education & Academia            black  hindu_jain_sikh    424  0.488208
3    Education & Academia            black           jewish   1735  0.490490
4    Education & Academia            black          teacher   1865  0.495979
..                    ...              ...              ...    ...       ...
145    Travel & Geography     construction           jewish   1093  0.480329
146    Travel & Geography     construction          teacher   1136  0.504401
147    Travel & Geography  hindu_jain_sikh           jewish    438  0.520548
148    Travel & Geography  hindu_jain_sikh          teacher    438  0.458904
149    Travel & Geography           jewish          teacher   1828  0.493982

[150 rows x 5 columns]

Split: Split by (category, unique demographic)

                                 category unique_demographic  count  accuracy
0                     Technology & Gaming       construction   5073  0.502464
1                     Technology & Gaming           catholic   7235  0.499378
2                     Technology & Gaming    hindu_jain_sikh   2784  0.489583
3                     Technology & Gaming            teacher   7009  0.493936
4                     Technology & Gaming              black   6748  0.499111
5                     Technology & Gaming             jewish   6807  0.493463
6                    Education & Academia       construction   4552  0.488796
7                    Education & Academia           catholic   7219  0.506303
8                    Education & Academia    hindu_jain_sikh   2120  0.481132
9                    Education & Academia            teacher   7233  0.502972
10                   Education & Academia              black   6907  0.497032
11                   Education & Academia             jewish   6907  0.492689
12                     Travel & Geography       construction   4923  0.500102
13                     Travel & Geography           catholic   7238  0.501934
14                     Travel & Geography    hindu_jain_sikh   2190  0.492237
15                     Travel & Geography            teacher   7216  0.495150
16                     Travel & Geography              black   6836  0.499269
17                     Travel & Geography             jewish   6923  0.500217
18                  News & Current Events       construction   4724  0.491321
19                  News & Current Events           catholic   7226  0.491835
20                  News & Current Events    hindu_jain_sikh   2445  0.483027
21                  News & Current Events            teacher   7220  0.505402
22                  News & Current Events              black   6657  0.493015
23                  News & Current Events             jewish   6872  0.495780
24                       Sports & Fitness       construction   5091  0.488902
25                       Sports & Fitness           catholic   7232  0.507605
26                       Sports & Fitness    hindu_jain_sikh   2475  0.507475
27                       Sports & Fitness            teacher   7227  0.498270
28                       Sports & Fitness              black   6704  0.498210
29                       Sports & Fitness             jewish   6641  0.499172
30                          Humor & Memes       construction   5812  0.498279
31                          Humor & Memes           catholic   7230  0.500000
32                          Humor & Memes    hindu_jain_sikh   2297  0.502830
33                          Humor & Memes            teacher   7202  0.497778
34                          Humor & Memes              black   6389  0.516982
35                          Humor & Memes             jewish   6506  0.498924
36                  Entertainment & Media       construction   5217  0.501246
37                  Entertainment & Media           catholic   7219  0.501454
38                  Entertainment & Media    hindu_jain_sikh   2165  0.491917
39                  Entertainment & Media            teacher   7223  0.501869
40                  Entertainment & Media              black   6830  0.504100
41                  Entertainment & Media             jewish   6646  0.500752
42            Hobbies & Special Interests       construction   5368  0.500745
43            Hobbies & Special Interests           catholic   7242  0.514361
44            Hobbies & Special Interests    hindu_jain_sikh   1900  0.520000
45            Hobbies & Special Interests            teacher   7242  0.512842
46            Hobbies & Special Interests              black   6882  0.502180
47            Hobbies & Special Interests             jewish   6546  0.505194
48                    Finance & Investing       construction   5038  0.488487
49                    Finance & Investing           catholic   7232  0.490321
50                    Finance & Investing    hindu_jain_sikh   2645  0.499811
51                    Finance & Investing            teacher   7214  0.502495
52                    Finance & Investing              black   6650  0.500000
53                    Finance & Investing             jewish   6821  0.492157
54  Professional & Career-oriented Spaces       construction   4852  0.487016
55  Professional & Career-oriented Spaces           catholic   7236  0.490879
56  Professional & Career-oriented Spaces    hindu_jain_sikh   2418  0.491315
57  Professional & Career-oriented Spaces            teacher   7233  0.496474
58  Professional & Career-oriented Spaces              black   6879  0.490042
59  Professional & Career-oriented Spaces             jewish   6804  0.494268

Split: Split by (description, unique demographic)

      description unique_demographic  count  accuracy
0     3D Printing       construction    360  0.513889
1     3D Printing           catholic    359  0.481894
2     3D Printing    hindu_jain_sikh     80  0.437500
3     3D Printing            teacher    360  0.480556
4     3D Printing              black    280  0.514286
...           ...                ...    ...       ...
1195         Yoga           catholic    362  0.483425
1196         Yoga    hindu_jain_sikh    225  0.493333
1197         Yoga            teacher    362  0.439227
1198         Yoga              black    344  0.468023
1199         Yoga             jewish    314  0.509554

[1200 rows x 4 columns]

Split: Split by (description, demographic_A, demographic_B)

      description    demographic_A    demographic_B  count  accuracy
0     3D Printing            black         catholic     66  0.530303
1     3D Printing            black     construction     66  0.530303
2     3D Printing            black  hindu_jain_sikh     16  0.500000
3     3D Printing            black           jewish     66  0.530303
4     3D Printing            black          teacher     66  0.469697
...           ...              ...              ...    ...       ...
2995         Yoga     construction           jewish     56  0.428571
2996         Yoga     construction          teacher     56  0.410714
2997         Yoga  hindu_jain_sikh           jewish     45  0.600000
2998         Yoga  hindu_jain_sikh          teacher     45  0.488889
2999         Yoga           jewish          teacher     71  0.507042

[3000 rows x 5 columns]